name: Deploy Front Productos

on:
  push:
    branches:
      - main

env:
  HOST: ${{ secrets.HOST_NAME }}
  ENV: ${{ secrets.ENV }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Clonar o actualizar repositorio en servidor
        run: |
          ssh -o StrictHostKeyChecking=no laura@$HOST << 'EOF'
            cd /home/laura/front-productos-docker || mkdir -p /home/laura/front-productos-docker && cd /home/laura/front-productos-docker

            if [ -d .git ]; then
              git pull
            else
              git clone https://github.com/LauraGabrielSantes/front-productos-docker .
            fi
          EOF

      - name: Crear .env localmente
        run: |
          echo "$ENV" > .env
          head -n 2 .env  # Para verificar que no esté vacío

      - name: Copiar .env al servidor
        run: |
          scp -o StrictHostKeyChecking=no .env laura@$HOST:/home/laura/front-productos-docker/.env

      - name: Levantar contenedores en el servidor
        run: |
          ssh -o StrictHostKeyChecking=no laura@$HOST << 'EOF'
            cd /home/laura/front-productos-docker
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
          EOF
